class FinalProfileData(object):
    def __init__(self):
        self.name = "NIL"
	self.profileFullName = "NIL"
	self.title = "NIL"
        self.location = "NIL"
	self.industry = "NIL"
        self.li_profile_link = "NIL"
        self.current_work = "NIL"
        self.past_work = "NIL"
        self.num_connections = "NIL"	
        self.summary = "NIL"
        self.education = "NIL"
	self.experience = "NIL"
	self.current_title = "NIL"
        self.skills = "NIL"
	self.downloadDate = "NIL"
	self.photoPresent = "N"
	self.photoFileName = "NIL"
	self.professionGeneral = "NIL"
	self.professionTitle = "NIL"
	self.professionSpec = "NIL"
	self.workingStatus = "NIL"
	self.industryMatch = "NIL"
	self.geography = "NIL"
	self.nonProfession = "NIL"
	self.workLocation = "NIL"
	self.match = "NIL"
	self.profileAssignment = "NIL"
	self.numDoctorsInFile = "NIL"
	self.numProfiles = 0
	self.remove = "false"

